# Dependencies
markdown:         kramdown
highlighter:      pygments

# Site settings
title: Rtist
description: >
  Abstract paintings and plots in R by Gaston Sanchez
baseurl: "http://gastonsanchez.com/Rtist"
url: "http://gastonsanchez.com/Rtist"

sass:
  style: compressed
